from pydantic import BaseModel, Field
from app.schemas.candidate import CandidateProfile
from app.schemas.skill_match import SkillMatch
from app.schemas.recommendation import Recommendation


class MatchReport(BaseModel):
    """
    Final evaluation report generated by the MatchingAgent.
    """
    candidate: CandidateProfile
    overall_score: float = Field(description="Overall compatibility score (0-100)")
    skill_match: SkillMatch = Field(description="Detailed skill matching results")
    recommendation: Recommendation = Field(description="Final hiring recommendation")
    explanation: str = Field(description="Human-readable explanation of the decision")